#!/usr/bin/python
"""Amulet tests on a basic openvswitch ODL deployment on trusty-icehouse."""

from basic_deployment import NeutronAPIODLBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIODLBasicDeployment(series='trusty')
    deployment.run_tests()
